export {payment as PaymentPage} from './payment'
export {board as BoardPage} from './board'
export {transaction as TransactionsPage} from './transaction'
export {reports as ReportsPage} from './reports'
export {settings as SettingsPage} from './settings'
